# Generated by Django 5.1 on 2024-08-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('materials', models.CharField(default=False, max_length=200)),
                ('material_sub_type', models.CharField(max_length=50)),
                ('thickness', models.DecimalField(decimal_places=2, default=0.0, help_text='Thickness in mm', max_digits=5)),
                ('finish', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, default=0.0, help_text='Length in mm', max_digits=255)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, help_text='Width in mm', max_digits=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Cost in #', max_digits=8)),
                ('vendor', models.CharField(default=False, max_length=200)),
            ],
        ),
    ]
