# Generated by Django 5.1 on 2024-08-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='user',
            new_name='user_type',
        ),
    ]
